print('')
print('             WELCOME!!! TO $ TUCO-UNIT-CONVERTER $ ')
print('')
NAME = input('CAN WE KNOW YOUR NAME PLEASE !!! ? >>> ')
print('')
NAME = NAME.upper()
print(f'               Welcome! {NAME}')
print('')
print('            WE ARE GLAD TO SEE YOU HERE !')
print('')
print('## THIS IS A UNIT CONVERTER THATS CONVERTS -KILOMETRE- TO -MILES- AND VICE-VERSA ##. ')
print('')
print('YOU JUST NEED TO INPUT YOUR VALUES BELOW AND IT WILL GET IT DONE ')

KILOMETRE = float(input('Input kilometre value >>>'))
print('')
MILES = float(input('Input miles value >>>>'))

KILOMETRE_TO_MILES = KILOMETRE*0.6237
MILES_TO_KILOMETRE = MILES*0.8726
print('')
print('PROCESSING..DATA........###############################################100%DONE')
print('CONVERTING........###############################################100%DONE')
print('')
print(f'THE VALUE OF KILOMETRE >>({KILOMETRE}km)<< CONVERTED TO MILES IS >>>{KILOMETRE_TO_MILES : .2f}miles<<<')
print('')
print('')
print('PROCESSIND..DATA........###############################################100%DONE')
print('CONVERTING........###############################################100%DONE')
print('')
print(f'THE VALUE OF MILES >>{MILES}miles<< CONVERTED TO KILOMETRE IS >>>{MILES_TO_KILOMETRE : .2f}km<<<')
print('')
print(f'             THANKS! FOR USING OUR PROGRAM. SEE YOU SOON ==> ')